# Generated by Django 6.0.2 on 2026-04-04 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcita',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
