# Generated by Django 6.0.2 on 2026-04-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_barbero_alter_cita_cliente_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.cita'),
        ),
    ]
