# Generated by Django 6.0.2 on 2026-04-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
