# Generated by Django 6.0.2 on 2026-04-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
        ('citas', '0001_initial'),
        ('usuarios', '0004_usuario_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_barbero', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_cliente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.servicio'),
        ),
    ]
