# Generated by Django 6.0.2 on 2026-04-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_barbero_alter_cita_cliente_and_more'),
        ('usuarios', '0004_usuario_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_cliente', to='usuarios.usuario'),
        ),
    ]
